[phases.build]
cmd = "npm run build"

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm run start:prod"

[build]
cmd = "npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
